-- Regalia Hotel Seed Data
-- Rooms, categories, and default admin/staff accounts
USE regalia_hotel;

-- ========== ROOM CATEGORIES ==========
INSERT INTO room_categories (name, description, base_rate) VALUES
('Classic Suite', 'Elegant classic suite with refined amenities and city views', 8500.00),
('Deluxe Suite', 'Spacious deluxe suite with premium furnishings', 12500.00),
('Premium Suite', 'Premium suite with luxury appointments and garden views', 16000.00),
('Executive Suite', 'Executive suite designed for business travelers', 18500.00),
('Royal Suite', 'Ultra-luxurious royal suite with exclusive amenities', 28000.00),
('Presidential Suite', 'The pinnacle of luxury accommodation', 45000.00);

-- ========== ROOMS (23 total) ==========

-- FLOOR 1 (Rooms 101-105) - Classic Suites
INSERT INTO rooms (room_number, floor, category_id, suite_category, status, nightly_rate, description, max_occupancy, dimensions, amenities, image_url, view_type, bed_type) VALUES
('101', 1, 1, 'Classic Suite', 'available', 8500.00, 'A beautifully appointed Classic Suite featuring warm ivory interiors, handcrafted wooden furnishings, and views of the hotel courtyard gardens. Perfect for the discerning traveler seeking refined comfort in the heart of Kolkata.', 2, '32 sqm', 'Wi-Fi, Smart TV, Mini Bar, Tea/Coffee Maker, Safe, Air Conditioning, Room Service', 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800', 'Garden View', 'King Bed'),
('102', 1, 1, 'Classic Suite', 'available', 8500.00, 'Charming Classic Suite with soft cream and gold accents, plush bedding, and a marble-appointed bathroom. Offers a tranquil retreat overlooking the lush greenery of the Royal Avenue precinct.', 2, '32 sqm', 'Wi-Fi, Smart TV, Mini Bar, Tea/Coffee Maker, Safe, Air Conditioning, Room Service', 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800', 'Garden View', 'King Bed'),
('103', 1, 1, 'Classic Suite', 'available', 9000.00, 'Inviting Classic Suite with elegant décor inspired by Kolkata rich cultural heritage. Features warm lighting, premium linens, and a spacious work desk.', 2, '34 sqm', 'Wi-Fi, Smart TV, Mini Bar, Tea/Coffee Maker, Safe, Air Conditioning, Work Desk, Room Service', 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?w=800', 'City View', 'King Bed'),
('104', 1, 1, 'Classic Suite', 'available', 8500.00, 'A serene Classic Suite offering peaceful garden views and timeless elegance. Ideal for solo travelers or couples seeking a restful Kolkata escape.', 2, '32 sqm', 'Wi-Fi, Smart TV, Mini Bar, Tea/Coffee Maker, Safe, Air Conditioning, Room Service', 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800', 'Garden View', 'Twin Beds'),
('105', 1, 1, 'Classic Suite', 'available', 8500.00, 'Tastefully designed Classic Suite with contemporary touches and traditional charm. Features a comfortable seating area and premium bathroom amenities.', 2, '32 sqm', 'Wi-Fi, Smart TV, Mini Bar, Tea/Coffee Maker, Safe, Air Conditioning, Room Service', 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800', 'Courtyard View', 'King Bed');

-- FLOOR 2 (Rooms 201-205) - Deluxe Suites
INSERT INTO rooms (room_number, floor, category_id, suite_category, status, nightly_rate, description, max_occupancy, dimensions, amenities, image_url, view_type, bed_type) VALUES
('201', 2, 2, 'Deluxe Suite', 'available', 12500.00, 'Expansive Deluxe Suite with separate living area, designer furnishings, and panoramic views of the Kolkata city skyline. A perfect blend of modern luxury and Bengali artistic flair.', 3, '45 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Room Service', 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800', 'City Skyline View', 'King Bed'),
('202', 2, 2, 'Deluxe Suite', 'available', 12500.00, 'Sophisticated Deluxe Suite featuring rich textures, gold-accented décor, and a luxurious marble bathroom with rain shower. Overlooks the vibrant Royal Avenue boulevard.', 3, '45 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Room Service', 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800', 'Boulevard View', 'King Bed'),
('203', 2, 2, 'Deluxe Suite', 'available', 13000.00, 'Luxurious Deluxe Suite with an open-plan layout, elegant chandelier lighting, and floor-to-ceiling windows showcasing Kolkata cityscape.', 3, '48 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Room Service', 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800', 'City View', 'King Bed + Sofa Bed'),
('204', 2, 2, 'Deluxe Suite', 'available', 12500.00, 'Refined Deluxe Suite with a calming palette of ivory and champagne tones, premium Egyptian cotton bedding, and curated Kolkata-inspired artwork.', 3, '45 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Room Service', 'https://images.unsplash.com/photo-1560185893-a55cbc8c57e8?w=800', 'Garden View', 'King Bed'),
('205', 2, 2, 'Deluxe Suite', 'available', 12500.00, 'Graceful Deluxe Suite offering a private balcony, sumptuous seating nook, and views of the hotel manicured landscape. A haven of luxury in Kolkata.', 3, '45 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Balcony, Room Service', 'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?w=800', 'Garden View', 'King Bed');

-- FLOOR 3 (Rooms 301-305) - Premium & Executive Suites
INSERT INTO rooms (room_number, floor, category_id, suite_category, status, nightly_rate, description, max_occupancy, dimensions, amenities, image_url, view_type, bed_type) VALUES
('301', 3, 3, 'Premium Suite', 'available', 16000.00, 'Sumptuous Premium Suite with a spacious living room, dining area, and sweeping views of the Kolkata city and garden landscape. Features bespoke furniture and handwoven textiles.', 3, '55 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, Butler Service, Room Service', 'https://images.unsplash.com/photo-1582719508461-900522c89192?w=800', 'City & Garden View', 'King Bed'),
('302', 3, 3, 'Premium Suite', 'available', 16000.00, 'Exquisite Premium Suite adorned with Kolkata artisan crafts, rich fabrics, and a private terrace. The perfect sanctuary for those who appreciate the finer things.', 3, '55 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, Private Terrace, Butler Service, Room Service', 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800', 'Terrace View', 'King Bed'),
('303', 3, 4, 'Executive Suite', 'available', 18500.00, 'Executive Suite designed for the modern business traveler. Features a dedicated workspace with ergonomic chair, high-speed internet, and access to the Executive Lounge.', 3, '58 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Executive Work Desk, Ergonomic Chair, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, Executive Lounge Access, Butler Service, Room Service', 'https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800', 'City View', 'King Bed'),
('304', 3, 4, 'Executive Suite', 'available', 18500.00, 'Premier Executive Suite with separate meeting area, premium sound system, and stunning views of the Kolkata luxury district. Ideal for executives and VIPs.', 3, '60 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Executive Work Desk, Meeting Area, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, Executive Lounge Access, Butler Service, Room Service', 'https://images.unsplash.com/photo-1594563703937-fdc640497dcd?w=800', 'City Skyline View', 'King Bed'),
('305', 3, 3, 'Premium Suite', 'available', 16500.00, 'A grand Premium Suite featuring opulent décor, a luxurious soaking tub, and curated views of the Royal Avenue gardens. An oasis of indulgence and comfort.', 3, '56 sqm', 'Wi-Fi, Smart TV, Mini Bar, Nespresso Machine, Safe, Air Conditioning, Work Desk, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, Butler Service, Room Service', 'https://images.unsplash.com/photo-1590490359683-658d3d23f972?w=800', 'Garden View', 'King Bed');

-- FLOOR 4 (Rooms 401-404) - Presidential & Royal Suites
INSERT INTO rooms (room_number, floor, category_id, suite_category, status, nightly_rate, description, max_occupancy, dimensions, amenities, image_url, view_type, bed_type) VALUES
('401', 4, 6, 'Presidential Suite', 'available', 45000.00, 'The crown jewel of Regalia Hotel. This magnificent Presidential Suite features a grand living room, private dining hall, study, and panoramic views of Kolkata. Handcrafted Italian marble, Swarovski chandeliers, and a personal butler ensure an unparalleled experience.', 4, '120 sqm', 'Wi-Fi, Smart TV, Full Bar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Private Dining Room, Bathrobe & Slippers, Hermès Toiletries, Jacuzzi & Steam Shower, 24/7 Butler Service, Private Elevator Access, Limousine Service, Room Service', 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&preset=premium', 'Panoramic City View', 'Emperor Bed'),
('402', 4, 6, 'Presidential Suite', 'available', 45000.00, 'An exquisite Presidential Suite offering the ultimate in luxury. Featuring a master bedroom, guest room, private lounge, and wraparound terrace with Kolkata skyline views.', 4, '125 sqm', 'Wi-Fi, Smart TV, Full Bar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Private Lounge, Bathrobe & Slippers, Hermès Toiletries, Jacuzzi & Steam Shower, 24/7 Butler Service, Private Elevator Access, Limousine Service, Room Service', 'https://images.unsplash.com/photo-1582719508461-900522c89192?w=800&preset=premium', 'Skyline View', 'Emperor Bed'),
('403', 4, 5, 'Royal Suite', 'available', 28000.00, 'The Royal Kolkata Enclave Suite. A majestic retreat featuring regal décor, a private sitting room, and breathtaking views of the city. Every detail reflects the grandeur of Kolkata royal heritage.', 4, '85 sqm', 'Wi-Fi, Smart TV, Premium Bar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, 24/7 Butler Service, Private Elevator Access, Room Service', 'https://images.unsplash.com/photo-1611892440504-42a792e24d32?w=800&preset=premium', 'City View', 'Super King Bed'),
('404', 4, 5, 'Royal Suite', 'available', 28000.00, 'A palatial Royal Suite inspired by the architectural splendor of Kolkata. Features ornate moldings, silk draperies, a grand piano, and a private library corner.', 4, '88 sqm', 'Wi-Fi, Smart TV, Premium Bar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Private Library, Bathrobe & Slippers, Premium Toiletries, Jacuzzi Tub, 24/7 Butler Service, Room Service', 'https://images.unsplash.com/photo-1596394516093-501ba68a0ba6?w=800&preset=premium', 'Garden & City View', 'Super King Bed');

-- FLOOR 5 (Rooms 501-503) - Ultra-Premium Royal Suites
INSERT INTO rooms (room_number, floor, category_id, suite_category, status, nightly_rate, description, max_occupancy, dimensions, amenities, image_url, view_type, bed_type) VALUES
('501', 5, 5, 'Royal Suite', 'available', 32000.00, 'The pinnacle Royal Suite on the top floor offering unobstructed 360-degree views of Kolkata. Features a private rooftop terrace, infinity plunge pool, and dedicated concierge service.', 4, '95 sqm', 'Wi-Fi, Smart TV, Full Bar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Private Terrace, Plunge Pool, Bathrobe & Slippers, Hermès Toiletries, Jacuzzi & Steam Shower, 24/7 Butler & Concierge, Private Elevator, Limousine Service, Room Service', 'https://images.unsplash.com/photo-1591088398332-8a7791972843?w=800&preset=premium', '360° Panoramic View', 'Emperor Bed'),
('502', 5, 5, 'Royal Suite', 'available', 30000.00, 'An extraordinary Royal Suite featuring floor-to-ceiling windows, a private art gallery, and Kolkata finest luxury appointments. A residence befitting royalty.', 4, '92 sqm', 'Wi-Fi, Smart TV, Full Bar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Private Art Gallery, Bathrobe & Slippers, Hermès Toiletries, Jacuzzi & Steam Shower, 24/7 Butler Service, Private Elevator, Room Service', 'https://images.unsplash.com/photo-1578683010236-d716f9a3f461?w=800&preset=premium', 'Panoramic City View', 'Emperor Bed'),
('503', 5, 6, 'Presidential Suite', 'available', 50000.00, 'The Grand Regalia Presidential Suite — the most exclusive accommodation in Kolkata. Two master bedrooms, a private cinema room, rooftop garden, and helipad access. The epitome of Indian luxury hospitality.', 6, '150 sqm', 'Wi-Fi, Smart TV, Full Bar & Wine Cellar, Nespresso Machine, Safe, Climate Control, Executive Work Desk, Private Cinema, Rooftop Garden, Bathrobe & Slippers, Hermès Toiletries, Jacuzzi & Steam Shower, 24/7 Butler & Concierge, Private Elevator, Helipad Access, Limousine Service, Room Service', 'https://images.unsplash.com/photo-1631049552057-403cdb8f0658?w=800&preset=premium', 'Panoramic Skyline View', 'Emperor Bed');
